sudo: required

services:
  - docker

language: go

notifications:
  email: true

go:
  - '1.14'

go_import_path: github.com/aledbf/kube-keepalived-vip

env:
  global:
    # to add additional secure variables:
    # docker run --rm caktux/travis-cli encrypt key=value -r kube-keepalived-vip
    - RELEASE="ci-${TRAVIS_BUILD_ID}"

jobs:
  include:
    - stage: Static Check
      script:
        - go get golang.org/x/lint/golint
        - make fmt lint vet
    - stage: Coverage
      script:
        - go get github.com/mattn/goveralls
        - go get github.com/modocache/gover
        - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
        - make cover
